[Icon Theme]
Name=Surfn Plasma Dark Breeze

Comment=Surfn Plasma Dark - depends on breeze-dark, breeze and Surfn

DisplayDepth=32

Inherits=breeze-dark,breeze,hicolor

Example=folder

FollowsColorScheme=true

DesktopDefault=48
DesktopSizes=16,22,32,48,64,128,256
ToolbarDefault=22
ToolbarSizes=16,22,32,48
MainToolbarDefault=22
MainToolbarSizes=16,22,32,48
SmallDefault=16
SmallSizes=16,22,32,48
PanelDefault=48
PanelSizes=16,22,32,48,64,128,256
DialogDefault=32
DialogSizes=16,22,32,48,64,128,256

#KDE-Extensions=.svg

########## Directories
########## ordered by category and alphabetically

Directories=actions/12,actions/16,actions/22,actions/24,actions/32,actions/64,animations/16,animations/22,apps/16,apps/22,apps/24,apps/32,status/16,status/22,status/24,status/32,status/48,status/64,actions/symbolic
ScaledDirectories=actions/16@2x,actions/16@3x,actions/22@2x,actions/22@3x,actions/24@2x,actions/24@3x,actions/32@2x,actions/32@3x,animations/16@2x,animations/16@3x,apps/16@2x,apps/16@3x,apps/22@2x,apps/22@3x,apps/24@2x,apps/24@3x,status/16@2x,status/16@3x,status/22@2x,status/22@3x

########## Actions
########## ordered by size

#12x12 - Fixed size - For Inkscape
[actions/12]
Size=12
Context=Actions
Type=Fixed

#16x16 - Fixed size - For use in sidebar(s) smaller toolbar(s) >!!!ONLY!!!<: e.g. Kate movable sidebar/toolbar (search and replace, current project, etc.) or Juk tree view - DO_NOT_USE_ANYWHERE_ELSE - Monochrome
[actions/16]
Size=16
Context=Actions
Type=Fixed

#16x16@2x - Fixed size - For use in sidebar(s) smaller toolbar(s) >!!!ONLY!!!<: e.g. Kate movable sidebar/toolbar (search and replace, current project, etc.) or Juk tree view - DO_NOT_USE_ANYWHERE_ELSE - Monochrome
[actions/16@2x]
Size=16
Scale=2
Context=Actions
Type=Fixed

#16x16@3x - Fixed size - For use in sidebar(s) smaller toolbar(s) >!!!ONLY!!!<: e.g. Kate movable sidebar/toolbar (search and replace, current project, etc.) or Juk tree view - DO_NOT_USE_ANYWHERE_ELSE - Monochrome
[actions/16@3x]
Size=16
Scale=3
Context=Actions
Type=Fixed

#22x22 - Fixed size - For toolbar icons >!!!ONLY!!!< - DO_NOT_USE_ANYWHERE_ELSE - Monochrome
[actions/22]
Size=22
Context=Actions
Type=Fixed

#22x22@2x - Fixed size - For toolbar icons >!!!ONLY!!!< - DO_NOT_USE_ANYWHERE_ELSE - Monochrome
[actions/22@2x]
Size=22
Scale=2
Context=Actions
Type=Fixed

#22x22@3x - Fixed size - For toolbar icons >!!!ONLY!!!< - DO_NOT_USE_ANYWHERE_ELSE - Monochrome
[actions/22@3x]
Size=22
Scale=3
Context=Actions
Type=Fixed

#24x24 - Fixed size - GTK icons >!!!ONLY!!!< - DO_NOT_USE_ANYWHERE_ELSE - Monochrome
[actions/24]
Size=24
Context=Actions
Type=Fixed

#24x24@2x - Fixed size - GTK icons >!!!ONLY!!!< - DO_NOT_USE_ANYWHERE_ELSE - Monochrome
[actions/24@2x]
Size=24
Scale=2
Context=Actions
Type=Fixed

#24x24@3x - Fixed size - GTK icons >!!!ONLY!!!< - DO_NOT_USE_ANYWHERE_ELSE - Monochrome
[actions/24@3x]
Size=24
Scale=3
Context=Actions
Type=Fixed

#32x32 - Fixed size - For toolbar icons >!!!ONLY!!!< - DO_NOT_USE_ANYWHERE_ELSE - Monochrome
[actions/32]
Size=32
Context=Actions
Type=Scalable
MinSize=32
MaxSize=256

#32x32@2x - Fixed size - For toolbar icons >!!!ONLY!!!< - DO_NOT_USE_ANYWHERE_ELSE - Monochrome
[actions/32@2x]
Size=32
Scale=2
Context=Actions
Type=Scalable
MinSize=32
MaxSize=256

#32x32@3x - Fixed size - For toolbar icons >!!!ONLY!!!< - DO_NOT_USE_ANYWHERE_ELSE - Monochrome
[actions/32@3x]
Size=32
Scale=3
Context=Actions
Type=Scalable
MinSize=32
MaxSize=256

#64x64 - Fixed size - For toolbar icons >!!!ONLY!!!< - DO_NOT_USE_ANYWHERE_ELSE - Monochrome
[actions/64]
Size=64
Context=Actions
Type=Scalable
MinSize=32
MaxSize=256

########## Animations
########## ordered by size

#16x16 - Fixed size - Application icon(s) for Dolphin sidebar - OPTIONAL + DO_NOT_USE_ANYWHERE_ELSE - Monochrome
[animations/16]
Size=16
Context=Animations
Type=Fixed

#16x16@2x - Fixed size - Application icon(s) for Dolphin sidebar - OPTIONAL + DO_NOT_USE_ANYWHERE_ELSE - Monochrome
[animations/16@2x]
Size=16
Scale=2
Context=Animations
Type=Fixed

#16x16@3x - Fixed size - Application icon(s) for Dolphin sidebar - OPTIONAL + DO_NOT_USE_ANYWHERE_ELSE - Monochrome
[animations/16@3x]
Size=16
Scale=3
Context=Animations
Type=Fixed

#22x22 - Scalable
[animations/22]
Size=22
Context=Animations
Type=Scalable
MinSize=22
MaxSize=256

########## Apps
########## ordered by size

#16x16 - Fixed size - Application icon(s) for Dolphin sidebar - OPTIONAL + DO_NOT_USE_ANYWHERE_ELSE - Monochrome
[apps/16]
Size=16
Context=Applications
Type=Fixed

#16x16@2x - Fixed size - Application icon(s) for Dolphin sidebar - OPTIONAL + DO_NOT_USE_ANYWHERE_ELSE - Monochrome
[apps/16@2x]
Size=16
Scale=2
Context=Applications
Type=Fixed

#16x16@3x - Fixed size - Application icon(s) for Dolphin sidebar - OPTIONAL + DO_NOT_USE_ANYWHERE_ELSE - Monochrome
[apps/16@3x]
Size=16
Scale=3
Context=Applications
Type=Fixed

#22x22 - Fixed size - Workaround icon(s) for toolbar(s) button(s) e.g. Dolphin Open Terminal/About Dolphin/About KDE buttons - WRONG_ICON_USAGE_BY_APP - Monochrome
[apps/22]
Size=22
Context=Applications
Type=Fixed

#22x22@2x - Fixed size - Workaround icon(s) for toolbar(s) button(s) e.g. Dolphin Open Terminal/About Dolphin/About KDE buttons - WRONG_ICON_USAGE_BY_APP - Monochrome
[apps/22@2x]
Size=22
Scale=2
Context=Applications
Type=Fixed

#22x22@3x - Fixed size - Workaround icon(s) for toolbar(s) button(s) e.g. Dolphin Open Terminal/About Dolphin/About KDE buttons - WRONG_ICON_USAGE_BY_APP - Monochrome
[apps/22@3x]
Size=22
Scale=3
Context=Applications
Type=Fixed

#24x24 - Fixed size - Workaround icon(s) for toolbar(s) button(s) e.g. Dolphin Open Terminal/About Dolphin/About KDE buttons - WRONG_ICON_USAGE_BY_APP - Monochrome
[apps/24]
Size=24
Context=Applications
Type=Fixed

#24x24@2x - Fixed size - Workaround icon(s) for toolbar(s) button(s) e.g. Dolphin Open Terminal/About Dolphin/About KDE buttons - WRONG_ICON_USAGE_BY_APP - Monochrome
[apps/24@2x]
Size=24
Scale=2
Context=Applications
Type=Fixed

#24x24@3x - Fixed size - Workaround icon(s) for toolbar(s) button(s) e.g. Dolphin Open Terminal/About Dolphin/About KDE buttons - WRONG_ICON_USAGE_BY_APP - Monochrome
[apps/24@3x]
Size=24
Scale=3
Context=Applications
Type=Fixed

#32x32 - Fixed size - For System Settings icons >!!!ONLY!!!< - Scalable to the following sizes: 32x32 (default), 64x64, 128x128, 256x256 - DO_NOT_USE_ANYWHERE_ELSE - Color
[apps/32]
Size=32
Context=Applications
Type=Fixed

#48x48 - Scalable - For application icons >!!!ONLY!!!< - Scalable to the following sizes: 48x48 (default), 96x96 and 24x24 (not recommended) - DO_NOT_USE_ANYWHERE_ELSE - Color
[apps/48]
Size=48
Context=Applications
Type=Scalable
MinSize=48
MaxSize=256

########## Status
########## ordered by size

#16x16 - Fixed size - For IM status icons >!!!ONLY!!!< - DO_NOT_USE_ANYWHERE_ELSE - Monochrome
[status/16]
Size=16
Context=Status
Type=Fixed

#16x16@2x - Fixed size - For IM status icons >!!!ONLY!!!< - DO_NOT_USE_ANYWHERE_ELSE - Monochrome
[status/16@2x]
Size=16
Scale=3
Context=Status
Type=Fixed

#16x16@3x - Fixed size - For IM status icons >!!!ONLY!!!< - DO_NOT_USE_ANYWHERE_ELSE - Monochrome
[status/16@3x]
Size=16
Scale=2
Context=Status
Type=Fixed

#22x22 - Fixed size - Icon(s) for Plasma theme/System Tray. Not particularly used on Plasma. - DO_NOT_USE_ANYWHERE_ELSE - Monochrome
[status/22]
Size=22
Context=Status
Type=Fixed

#22x22@2x - Fixed size - Icon(s) for Plasma theme/System Tray. Not particularly used on Plasma. - DO_NOT_USE_ANYWHERE_ELSE - Monochrome
[status/22@2x]
Size=22
Scale=2
Context=Status
Type=Fixed

#22x22@3x - Fixed size - Icon(s) for Plasma theme/System Tray. Not particularly used on Plasma. - DO_NOT_USE_ANYWHERE_ELSE - Monochrome
[status/22@3x]
Size=22
Scale=3
Context=Status
Type=Fixed

#24x24 - Fixed size - for GTK apps. - WRONG_ICON_USAGE_BY_APP - Monochrome
[status/24]
Size=24
Context=Status
Type=Fixed

#32x32 - Fixed size - Icon(s) for Plasma theme/System Tray. Not particularly used on Plasma. - DO_NOT_USE_ANYWHERE_ELSE - Monochrome
[status/32]
Size=32
Context=Status
Type=Fixed

#48x48 - Fixed size - For dialog icons >!!!ONLY!!!< - DO_NOT_USE_ANYWHERE_ELSE - Color
[status/48]
Size=48
Context=Status
Type=Fixed

#64x64 - Fixed size - For dialog icons >!!!ONLY!!!< - DO_NOT_USE_ANYWHERE_ELSE - Color
[status/64]
Size=64
Context=Status
Type=Scalable
MinSize=22
MaxSize=256

# Gnome symbolic icons

[actions/symbolic]
Context=Actions
Size=16
MinSize=8
MaxSize=512
Type=Scalable

[devices/symbolic]
Context=Devices
Size=16
MinSize=8
MaxSize=512
Type=Scalable

[emblems/symbolic]
Context=Emblems
Size=16
MinSize=8
MaxSize=512
Type=Scalable

[places/symbolic]
Context=Places
Size=16
MinSize=8
MaxSize=512
Type=Scalable

[status/symbolic]
Context=Status
Size=16
MinSize=8
MaxSize=512
Type=Scalable

########## EOF
