[Icon Theme]
Name=Surfn Plasma Dark Breeze

Comment=Surfn Plasma Dark - depends on breeze-dark, breeze and Surfn

DisplayDepth=32

Inherits=breeze-dark,breeze,hicolor

Example=folder

FollowsColorScheme=true

DesktopDefault=48
DesktopSizes=16,22,32,48,64,128,256
ToolbarDefault=22
ToolbarSizes=16,22,32,48
MainToolbarDefault=22
MainToolbarSizes=16,22,32,48
SmallDefault=16
SmallSizes=16,22,32,48
PanelDefault=48
PanelSizes=16,22,32,48,64,128,256
DialogDefault=32
DialogSizes=16,22,32,48,64,128,256

#KDE-Extensions=.svg

########## Directories
########## ordered by category and alphabetically

Directories=apps/16,apps/22,apps/24,apps/32,apps/48,apps/64,apps/16@2x,apps/16@3x,apps/22@2x,apps/22@3x,apps/24@2x,apps/24@3x

########## Apps
########## ordered by size

#16x16 - Fixed size - Application icon(s) for Dolphin sidebar - OPTIONAL + DO_NOT_USE_ANYWHERE_ELSE - Monochrome
[apps/16]
Size=16
Context=Applications
Type=Fixed

#16x16@2x - Fixed size - Application icon(s) for Dolphin sidebar - OPTIONAL + DO_NOT_USE_ANYWHERE_ELSE - Monochrome
[apps/16@2x]
Size=16
Scale=2
Context=Applications
Type=Fixed

#16x16@3x - Fixed size - Application icon(s) for Dolphin sidebar - OPTIONAL + DO_NOT_USE_ANYWHERE_ELSE - Monochrome
[apps/16@3x]
Size=16
Scale=3
Context=Applications
Type=Fixed

#22x22 - Fixed size - Workaround icon(s) for toolbar(s) button(s) e.g. Dolphin Open Terminal/About Dolphin/About KDE buttons - WRONG_ICON_USAGE_BY_APP - Monochrome
[apps/22]
Size=22
Context=Applications
Type=Fixed

#22x22@2x - Fixed size - Workaround icon(s) for toolbar(s) button(s) e.g. Dolphin Open Terminal/About Dolphin/About KDE buttons - WRONG_ICON_USAGE_BY_APP - Monochrome
[apps/22@2x]
Size=22
Scale=2
Context=Applications
Type=Fixed

#22x22@3x - Fixed size - Workaround icon(s) for toolbar(s) button(s) e.g. Dolphin Open Terminal/About Dolphin/About KDE buttons - WRONG_ICON_USAGE_BY_APP - Monochrome
[apps/22@3x]
Size=22
Scale=3
Context=Applications
Type=Fixed

#24x24 - Fixed size - Workaround icon(s) for toolbar(s) button(s) e.g. Dolphin Open Terminal/About Dolphin/About KDE buttons - WRONG_ICON_USAGE_BY_APP - Monochrome
[apps/24]
Size=24
Context=Applications
Type=Fixed

#24x24@2x - Fixed size - Workaround icon(s) for toolbar(s) button(s) e.g. Dolphin Open Terminal/About Dolphin/About KDE buttons - WRONG_ICON_USAGE_BY_APP - Monochrome
[apps/24@2x]
Size=24
Scale=2
Context=Applications
Type=Fixed

#24x24@3x - Fixed size - Workaround icon(s) for toolbar(s) button(s) e.g. Dolphin Open Terminal/About Dolphin/About KDE buttons - WRONG_ICON_USAGE_BY_APP - Monochrome
[apps/24@3x]
Size=24
Scale=3
Context=Applications
Type=Fixed

#32x32 - Fixed size - For System Settings icons >!!!ONLY!!!< - Scalable to the following sizes: 32x32 (default), 64x64, 128x128, 256x256 - DO_NOT_USE_ANYWHERE_ELSE - Color
[apps/32]
Size=32
Context=Applications
Type=Fixed

#48x48 - Scalable - For application icons >!!!ONLY!!!< - Scalable to the following sizes: 48x48 (default), 96x96 and 24x24 (not recommended) - DO_NOT_USE_ANYWHERE_ELSE - Color
[apps/48]
Size=48
Context=Applications
Type=Scalable
MinSize=48
MaxSize=256

#64x64 - Scalable - For application icons >!!!ONLY!!!< - Scalable to the following sizes: 48x48 (default), 96x96 and 24x24 (not recommended) - DO_NOT_USE_ANYWHERE_ELSE - Color
[apps/64]
Size=64
Context=Applications
Type=Scalable
MinSize=64
MaxSize=256